# Generated by Django 2.2.14 on 2023-07-04 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Smartwatch'), ('SW', 'Smartphone'), ('tv', 'Television'), ('wf', 'Woofer'), ('ot', 'Other Electronics')], max_length=2),
        ),
    ]
